### ISSUE TITLE
Blacklist the link title "Add Link", prevents confusion in case someone names all their links "Add Link" and because tests query for the button with "Add Link" text inside to automate link creation

### ISSUE THREAD

**Issue by ChannelJuanNews** [AZTechLabs/link#13]
This works, but doesn't give the user an error as to why they can't add this link

**Comment by ChannelJuanNews** [comment]
PART 1
1. Add a banned title entity inside of the entities folder `BannedTitle.ts`
2  Give this entity (aka table) a column of id & title 

PART 2
1. add.link.partial access the entity by importing it at the top 
2. just copy and paste from line 2 or 3 and change the names to match BannedTitle 

PART 3 
1. run a SQL query with EntityManager to check if the given input is inside of the banned title 
2. you can write the optimized query yourself (raw sql string) or use query builder to do keyword detection on the title (aka NN*ibba vs N*bba) 

PART 4. 
1. if the query returns true or whatever value that leads us to rejection, resolve the promise with an error and give a good error message 
2. if the query returns false, then do nothing and allow the rest of the resolver to execute

**Comment by Juan-M-Hernandez** [comment]
To prevent having to go through an entity manager I implemented a blacklist for link titles, fastest way while also avoiding regex checking

" Some people, when confronted with a problem, think ' I know, I'll use regular expressions.' Now they have two problems. " -Jamie Zawinski
