### ISSUE TITLE
Register w/ a Certificate Authority for a signed cert

### ISSUE THREAD

**Issue by Juan-M-Hernandez** [AZTechLabs/link#27]
TODO (Pre-Production Launch): Must register a public key with a Certificate Authority (CA) so that we can have a trusted and signed certificate, otherwise most browsers will warn users about a self signed certification

>>> https://letsencrypt.org/

**Comment by ChannelJuanNews** [comment]
we will use let's encrypt for staging and prod, for local dev we will use self-signed certs. Good thing you brought this forward!
