### ISSUE TITLE
Major bug: creating a new link without a title will make a users /profile inacccessible

### ISSUE THREAD

**Issue by Juan-M-Hernandez** [AZTechLabs/link#30]
Currently working on modularizing validation to prevent uncaught JS errors that may break our application.

Issue: Creating a new link without a title name but a valid url will not toss an error, it will store the link in our database. The error comes from trying to display the users links and some JS function is not properly wrapped in a try{} catch{}, once the link exists in our database our application can no longer render the users /profile page.

**Comment by Juan-M-Hernandez** [comment]
Update: Closer pinpoint -> regex sql query and validation are not properly hooked up, easy fix

**Comment by ChannelJuanNews** [comment]
@Juan-M-Hernandez make sure that this isn't the already documented issue of the link not being live. 

When the user has no links that are "live" (boolean set to true) it will error out.

**Comment by Juan-M-Hernandez** [comment]
No longer crashes after today's dev merge
