### ISSUE TITLE
/profile page username abbreviation is too long, overflows our avatar background (circle)

### ISSUE THREAD

**Issue by Juan-M-Hernandez** [AZTechLabs/link#9]
![Screenshot from 2021-03-17 20-47-08](https://user-images.githubusercontent.com/38334483/111556941-14c60a80-8762-11eb-98bf-b043a9b9b5ed.png)

**Comment by ChannelJuanNews** [comment]
I have created a fix to where we trim the username to the first 3 characters only. We can test this across platforms with different browsers but I think this fixes this issue. Will wait for feedback from your testing. 

<img width="1465" alt="Screen Shot 2021-03-18 at 12 46 20 AM" src="https://user-images.githubusercontent.com/5581443/111590509-6af77580-8783-11eb-8b87-c46d0ab459c5.png">

<img width="375" alt="Screen Shot 2021-03-18 at 12 46 13 AM" src="https://user-images.githubusercontent.com/5581443/111590525-6fbc2980-8783-11eb-8594-4cd9a8325473.png">

**Comment by Juan-M-Hernandez** [comment]
Confirmed fixed
